name: and_drum_pad_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.9.46
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  base_ui_flutter_v1:
    path: ../base_ui_flutter_v1
  intl: any
  flutter_localization: ^0.3.1
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  url_launcher: ^6.3.1
  flutter_easyloading: ^3.0.5
  in_app_review: ^2.0.10
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.1.0
  path_provider: ^2.1.5
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  purchases_flutter: ^8.6.0
  animated_flip_counter: ^0.3.4
  tutorial_coach_mark: ^1.2.13
  uuid: ^4.5.1
  permission_handler: ^11.4.0
  dio: ^5.8.0+1
  archive: ^4.0.5
  http: ^1.3.0
  marquee: ^2.3.0
  open_settings_plus: ^0.4.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_ce_generator: ^1.8.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/anim/
    - assets/
    - assets/audio/
    - assets/images/
    - assets/icons/
